volodya

false

# liquidatePartyA can be called after liquidatePositionsPartyA so partyA will be stuck in liquidateStatus forever I think

## Summary
Because of test `"Should fail to liquidate a user twice"`
E.x. partyA decided to invest more by allocating some sum. After that malicious liquidator will be able to freeze his account by calling liquidatePartyA
## Vulnerability Detail

## Impact

## Code Snippet

## Tool used
```diff
      it("Should liquidate positions", async function() {
        const context: RunContext = this.context;
        let user = context.signers.user.getAddress();
        let hedger = context.signers.hedger.getAddress();
        console.log(await this.user.getBalanceInfo());
        await context.liquidationFacet
          .connect(context.signers.liquidator)
          .liquidatePendingPositionsPartyA(user);

        await context.liquidationFacet
          .connect(context.signers.liquidator)
          .liquidatePositionsPartyA(user, [1]);

        expect((await context.viewFacet.getQuote(1)).quoteStatus).to.be.equal(
          QuoteStatus.LIQUIDATED,
        );
        expect(await context.viewFacet.allocatedBalanceOfPartyB(hedger, user)).to.be.equal(
          decimal(382),
        );
        let balanceInfoOfLiquidator = await this.liquidator.getBalanceInfo();
        expect(balanceInfoOfLiquidator.allocatedBalances).to.be.equal(decimal(1));
        
+        await liquidatePartyA(
+          context,
+          context.signers.user.getAddress(),
+        );
      });

```
Manual Review

## Recommendation
