ravikiran.web3

medium

# depositFor() function of AccountFacet does not check for zero address leading to loss of funds.

## Summary
Using AccountFacet, when a user wants to deposit funds to another user's account, there is no check for zero address and the funds are actually deposited to zero address and as no one has access to private keys of zero address, the funds are permanently lost.

## Vulnerability Detail
In order to protect customer funds, the contract should validate as much as feasible. 
During the deposit of funds by a user for another user using AccountFacet.depositFor(), the "to" address should be checked to be atleast non zero address.

But, such check is not there resulting in user funds moving to zero address account and those funds are lost permanently.


**POC:**
In the below poc, the user 2 is Zero address.
```javascript
 const user2 = ethers.constants.AddressZero;
```
User who has 300 tokens transfer them to User2, but sends to 0 address by mistake. Now,  user has permanently lost his funds
We can see the balance of 300 in zero address(User2).

With drawl will not work.
```javascript

it("Should fail if user being deposited for is zero address", async function() {
      const context: RunContext = this.context;
      const user = context.signers.user.getAddress();
      const user2 = ethers.constants.AddressZero;

      console.log("user2's address", await user2);
      console.log("user2's balance", await context.viewFacet.balanceOf(user2));
      console.log("user deposited balance for user 2");
      await context.accountFacet.connect(context.signers.user).depositFor(user2, "300");
      console.log("user has a balance", await context.viewFacet.balanceOf(user));
      console.log("user2's balance", await  context.viewFacet.balanceOf(user2));

      console.log("big mistake, user transfer funds to zero address, funds lost",await context.viewFacet.balanceOf(user2));
      console.log("no one has access to private keys of address 0, but there is a balance",await context.viewFacet.balanceOf(user2));

      // withdrawl fails.
      await context.accountFacet.connect(context.signers.user).withdrawTo(user2, "300");
      console.log("big mistake, user transfer funds to zero address, funds lost",await context.viewFacet.balanceOf(user2));
      console.log("no one has access to private keys of address 0, but there is a balance",await context.viewFacet.balanceOf(user2));
    });

```

Printed logs:

**user2's address 0x0000000000000000000000000000000000000000**
user2's balance BigNumber { value: "0" }
**user deposited balance for user 2**
user has a balance BigNumber { value: "0" }
**user2's balance BigNumber { value: "300" }**
big mistake, user transfer funds to zero address, funds lost BigNumber { value: "300" }
no one has access to private keys of address 0, but there is a balance BigNumber { value: "300" }

With drawl fails.

## Impact
Loss of user funds.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacet.sol#L21C1-L23

## Tool used

Manual Review

## Recommendation

```solidity
function depositFor(address user, uint256 amount) external whenNotAccountingPaused {
       require(user!=address(0),"Zero address not allowed");
        AccountFacetImpl.deposit(user, amount);
        emit Deposit(msg.sender, user, amount);
    }
```
